#!/usr/bin/env python3
"""Regenerate the app's launcher-icon and splash marks from their master artwork.

Three independent master PNGs live in `tools/master_art/`, checked into the repo (the
first generation of this pipeline read a master from wherever the operator happened to
have it and kept nothing in version control — that is exactly how the original art was
lost; see git history for `ic_launcher_background.xml`). Each was generated by an AI
image model against its own flat matte so the mark can be lifted off it with an alpha
key:

    tools/master_art/ic_launcher_foreground.png   the mark, on solid black
    tools/master_art/ic_launcher_monochrome.png   a white silhouette, on solid black
    tools/master_art/splash_graphic.png           the mark, on solid dark navy

Unlike the first generation, the monochrome mark is its own illustration rather than the
foreground's alpha channel flattened to white — the two differ slightly in pose. That is
a deliberate choice this time (see the commit that introduced this script), not a bug.

    python tools/generate_icons.py

Writes, relative to the repository root:

    app/src/main/res/mipmap-<density>/ic_launcher_foreground.webp   adaptive icon foreground
    app/src/main/res/mipmap-<density>/ic_launcher_monochrome.webp   themed-icon silhouette
    app/src/main/res/drawable-<density>/splash_logo.webp            splash mark

Nothing lands in -nodpi: that disables density stripping and ships every size to every
device (see AGENTS.md). Everything is written as lossless WebP.

The background layer (`ic_launcher_background.xml`) is deliberately NOT generated here.
It is a plain diagonal gradient with no fine detail, so it is hand-written as an Android
`<gradient>` vector instead of a raster: smaller, and perfectly sharp at every density.
See `app/src/main/res/drawable/ic_launcher_background.xml`.
"""

import sys
from pathlib import Path

import numpy as np
from PIL import Image

MASTER_DIR = Path(__file__).resolve().parent / "master_art"
RES_DIR = Path(__file__).resolve().parent.parent / "app" / "src" / "main" / "res"
REPO_ROOT = Path(__file__).resolve().parent.parent

# An adaptive icon is a 108dp canvas whose art must stay inside the centre 72dp; the rest
# can be cropped to any mask shape. 66.67% keeps the mark clear of every launcher shape.
SAFE_ZONE = 72 / 108

DENSITIES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}
FOREGROUND_DP = 108
SPLASH_DP = 200  # splash_icon_layer.xml draws the mark at 200dp; the composable uses 180dp.

# Alpha below this (out of 255) is noise from the key, not real edge softness.
ALPHA_FLOOR = 12

# The AI-generated masters carry faint grain across the *entire* canvas — imperceptible,
# but enough that a handful of pixels near ALPHA_FLOOR reach every edge, so a plain
# `Image.getbbox()` (any alpha > 0) returns the full canvas instead of the mark's real
# extent. Finding bounds at this much stricter level instead, then cropping the true
# soft-alpha image to that box (plus a small margin for real edge antialiasing), avoids
# it while still keeping smooth edges on the mark itself.
BBOX_ALPHA = 0.3
BBOX_MARGIN = 0.03  # fraction of the detected box's own size, added on every side


def key_out(master: Path, background: tuple, threshold: float) -> Image.Image:
    """Return the mark alone, on transparency, tightly cropped, keyed off a flat colour."""
    rgb = np.asarray(Image.open(master).convert("RGB")).astype(np.float64)
    bg = np.array(background, dtype=np.float64)

    alpha = np.clip(np.abs(rgb - bg).max(axis=2) / threshold, 0, 1)
    alpha[alpha * 255 < ALPHA_FLOOR] = 0.0

    # Unpremultiply so edge pixels keep their own colour instead of a blend with the
    # background they were lifted off — without this, edges pick up a dark/navy fringe.
    safe = np.maximum(alpha, 1e-6)[..., None]
    colour = np.clip(bg + (rgb - bg) / safe, 0, 255)

    mark = Image.fromarray(np.dstack([colour, alpha * 255]).astype(np.uint8))

    ys, xs = np.where(alpha > BBOX_ALPHA)
    if len(xs) == 0:
        raise ValueError(f"{master.name}: nothing survived the key — check threshold/background")
    x0, x1, y0, y1 = xs.min(), xs.max(), ys.min(), ys.max()
    mx, my = int((x1 - x0) * BBOX_MARGIN), int((y1 - y0) * BBOX_MARGIN)
    w, h = mark.size
    bbox = (max(0, x0 - mx), max(0, y0 - my), min(w, x1 + mx + 1), min(h, y1 + my + 1))
    return mark.crop(bbox)


def whiten(mark: Image.Image) -> Image.Image:
    """Flatten a keyed mark to solid white, keeping only its alpha shape (themed icons)."""
    flat = Image.new("RGBA", mark.size, (255, 255, 255, 0))
    flat.putalpha(mark.getchannel("A"))
    return flat


def fit(mark: Image.Image, canvas_px: int, content_fraction: float) -> Image.Image:
    """Centre the mark on a square transparent canvas, scaled to the given fraction."""
    target = int(round(canvas_px * content_fraction))
    scaled = mark.copy()
    scaled.thumbnail((target, target), Image.LANCZOS)
    canvas = Image.new("RGBA", (canvas_px, canvas_px), (0, 0, 0, 0))
    canvas.paste(
        scaled,
        ((canvas_px - scaled.size[0]) // 2, (canvas_px - scaled.size[1]) // 2),
        scaled,
    )
    return canvas


def write_densities(mark: Image.Image, dp: int, content_fraction: float, target) -> int:
    """`target(density)` returns the Path to write that density's WebP to."""
    written = 0
    for density, scale in DENSITIES.items():
        px = int(round(dp * scale))
        path = target(density)
        path.parent.mkdir(parents=True, exist_ok=True)
        fit(mark, px, content_fraction).save(path, "WEBP", lossless=True, quality=100, method=6)
        print(f"  {path.relative_to(REPO_ROOT)}  {path.stat().st_size:,} bytes")
        written += 1
    return written


def main() -> int:
    written = 0

    foreground = key_out(MASTER_DIR / "ic_launcher_foreground.png", background=(0, 0, 0), threshold=30)
    print(f"foreground mark: {foreground.size[0]}x{foreground.size[1]}")
    written += write_densities(
        foreground, FOREGROUND_DP, SAFE_ZONE,
        lambda d: RES_DIR / f"mipmap-{d}" / "ic_launcher_foreground.webp",
    )

    monochrome = whiten(key_out(MASTER_DIR / "ic_launcher_monochrome.png", background=(0, 0, 0), threshold=30))
    print(f"monochrome mark: {monochrome.size[0]}x{monochrome.size[1]}")
    written += write_densities(
        monochrome, FOREGROUND_DP, SAFE_ZONE,
        lambda d: RES_DIR / f"mipmap-{d}" / "ic_launcher_monochrome.webp",
    )

    splash = key_out(MASTER_DIR / "splash_graphic.png", background=(41, 51, 60), threshold=26)
    print(f"splash mark: {splash.size[0]}x{splash.size[1]}")
    written += write_densities(
        # SAFE_ZONE, not 1.0: the system SplashScreen API's windowSplashScreenAnimatedIcon
        # treats this the same way a launcher icon does and can mask it into a circle on
        # real devices (not reproduced on the emulator this was first built against) — a
        # mark that fills its box edge to edge gets its head and feet clipped by that mask.
        splash, SPLASH_DP, SAFE_ZONE,
        lambda d: RES_DIR / f"drawable-{d}" / "splash_logo.webp",
    )

    print(f"{written} files written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
